server:
  port: 9090

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8070/eureka/
spring:
  profiles:
    active:
      - "qa"
  application:
    name: cards
  jpa:
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8071
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      enabled: true
  info:
    env:
      enabled: true
  tracing:
    sampling:
          probability: 1.0
info:
  message: "welcome to cards application default profile"
  name: "raj default profile cards"



logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"